a = input()
b = input()
s = float(a) + float(b)
x = float(a)
y = int(b)
m = float(a) * float(b)
dn = float(a) / float(b)
di = float(a) // float(b)
ex = float(a) ** float(b)
r = float(a) % float(b)
print(s)
print(f'{x}{y}')
print(m)
print(f'{x}'*y)
print(dn)
print(di)
print(ex)
print(r)
